### ISSUE TITLE
关于代码实现和实验结果的一点疑问

### ISSUE THREAD

**Issue by stack-heap-overflow** [AI-confused/Sequence-to-Action#3]
感谢大佬开源的sequence-to-action论文复现工作，有几点疑问想问一下，希望能得到您的回复：
1. 原论文y_out中有[BLK]符号，但y_in中没有[BLK]，这在推理过程中是否会出现不一致的问题，推理过程中是如何处理的呢
2. 您提到该方法相比基线有所提升，请问是在比赛数据集上的结果吗，相比不使用seq2action大概提升了几个点呢
3. 该方法实现过程中您是否有遇到什么坑呢，比如模型结构、标签设计等方面

**Comment by AI-confused** [comment]
1.推理也有可能输出[BLK]，后处理去掉该字符即可，训练和推理是一致的，[BLK]是添加到词表中的；
2.基线的总分大概是36，该方法能达到39
3.model.py那部分代码特别复杂，涉及tensor的一些特殊操作，需要仔细看，因为论文在输出维度上做了裁剪和拼接、选择
希望能帮到你
