### ISSUE TITLE
能否分享工程中的json文件？

### ISSUE THREAD

**Issue by chunleicheng** [AI-confused/Sequence-to-Action#5]
谢谢大佬的分享，认真研读了您的代码，这个代码还是有些复杂，想看看您相关的几个json文件，可否分享一下，谢谢。我邮箱：313239535@qq.com。您代码中的几个json文件：
jianti_14-18_train+test_charlevel/detect_all_data_v3.jsonl
jianti_14-18_train+test_charlevel/detect_dev_v2.jsonl
train.jsonl
dev.jsonl

**Comment by AI-confused** [comment]
可以参考下这个仓库https://github.com/AI-confused/CCL2022_CGED-8_Top1_project/tree/main  的dataset和data_preprocess，之前的原始文件已经失传了😂

**Comment by chunleicheng** [comment]
这是来自QQ邮箱的自动回复邮件。您好，您的来信已经收到，程。

**Comment by chunleicheng** [comment]
谢谢您的分享
